Pim\Bundle\ApiBundle\Entity\Client:
    type: entity
    table: pim_api_client
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
